#!/usr/bin/env python3
"""
scripts/nifty_macro_to_micro_trap_backtest.py

Run the full macro-to-micro trap execution engine on NIFTY spot data:
  - Macro HTF: 75m / 150m / 225m structural bull/bear traps.
  - Re-entry into the validated trap zone.
  - V4 15m -> 5m cascade with 1/3 retracement limit trigger.
  - 1m micro trigger: close above prior 1m high (long) / below prior 1m low (short).
  - ADX < 22.5, RSI long > 40 / short < 60, VWAP-500 toggleable filters.
  - Retest void-lift target policy.

Outputs a macro-trap table and a performance summary (lot size = 75).
"""
from __future__ import annotations

import glob
import os
import sys
from datetime import date, time

import pandas as pd
import pytz

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from strategies.trap_scanner import v4_spot_cascade as v4

IST = pytz.timezone("Asia/Kolkata")
CACHE_DIR = os.path.join(ROOT, "data", "nse_option_cache")
OUTPUT_DIR = os.path.join(ROOT, "data")

START = date(2026, 6, 1)
END = date(2026, 7, 3)
MULTIPLIERS = [75, 150, 225]

MAX_ADX = 22.5
RSI_LONG_MIN = 40.0
RSI_SHORT_MAX = 60.0
USE_VWAP = True
USE_ADX = True
USE_RSI = True


def load_1m_spot(start: date, end: date) -> pd.DataFrame:
    files = sorted(glob.glob(os.path.join(CACHE_DIR, "spot_NIFTY_1m_*.parquet")))
    frames = []
    for f in files:
        df = pd.read_parquet(f)
        df["datetime"] = pd.to_datetime(df["datetime"])
        if df["datetime"].dt.tz is None:
            df["datetime"] = df["datetime"].dt.tz_localize(
                "Asia/Kolkata", ambiguous="NaT", nonexistent="shift_forward"
            )
        else:
            df["datetime"] = df["datetime"].dt.tz_convert("Asia/Kolkata")
        frames.append(df)

    df = pd.concat(frames, ignore_index=True)
    df = df.drop_duplicates("datetime").sort_values("datetime").reset_index(drop=True)
    df = df[(df["datetime"].dt.date >= start) & (df["datetime"].dt.date <= end)]
    df = df[(df["datetime"].dt.time >= time(9, 15)) & (df["datetime"].dt.time <= time(15, 30))]
    return df


def print_macro_table(macro_df: pd.DataFrame) -> None:
    if macro_df.empty:
        print("No macro structural traps detected.")
        return

    macro_df = macro_df.sort_values("trap_ts").reset_index(drop=True)
    fmt = lambda ts: ts.strftime("%Y-%m-%d %H:%M") if isinstance(ts, pd.Timestamp) else str(ts)[:16]

    header = (
        f"{'Ref Candle Time':<20} {'Breakout Candle Time':<20} {'Trap Confirmed Time':<20} "
        f"{'Trap Type':<12} {'Multiplier':<14} "
        f"{'Range Breakout Line':>18} {'Anchor SL Level':>16} "
        f"{'Peak Trap High/Low':>18} {'Validated Trap Zone':>22}"
    )
    print("\n" + header)
    print("-" * len(header))

    for _, r in macro_df.iterrows():
        peak_str = f"H {r['peak']:>14.2f}" if r['type'] == 'Bull' else f"L {r['peak']:>14.2f}"
        zone_str = f"{r['zone_low']:.2f} - {r['zone_high']:.2f}"
        print(
            f"{fmt(r['ref_ts']):<20} {fmt(r['breakout_ts']):<20} {fmt(r['confirm_ts']):<20} "
            f"{r['type']:<12} {r['multiplier']:<14} "
            f"{r['breakout_line']:>18.2f} {r['anchor_sl']:>16.2f} "
            f"{peak_str:>18} {zone_str:>22}"
        )

    print(f"\n{'Macro Trap Summary':=^60}")
    print(f"Total structural traps: {len(macro_df)}")
    print(f"  Bull traps: {sum(macro_df['type'] == 'Bull')}")
    print(f"  Bear traps: {sum(macro_df['type'] == 'Bear')}")
    for mult in MULTIPLIERS:
        cnt = sum(macro_df["multiplier"] == f"{mult}m")
        print(f"  {mult}m: {cnt}")


def print_trade_summary(trades_df: pd.DataFrame) -> None:
    if trades_df.empty:
        print("\nNo trades generated by the macro-to-micro engine.")
        return

    s = v4.summarize_macro_to_micro_trades(trades_df)
    print("\n" + "=" * 70)
    print("Macro-to-Micro Trade Summary (NIFTY spot, lot size = 75)")
    print("=" * 70)
    print(f"Total trades        : {s['total']}")
    print(f"Wins                : {s['wins']} ({s['win_rate']:.1f}%)")
    print(f"Losses              : {s['losses']}")
    print(f"Gross profit        : Rs. {s['gross_profit']:,.2f}")
    print(f"Gross loss          : Rs. {s['gross_loss']:,.2f}")
    print(f"Net P&L             : Rs. {s['net_pnl']:,.2f}")
    print(f"Profit factor       : {s['profit_factor']:.2f}")
    print(f"Avg win / avg loss  : Rs. {s['avg_win']:,.2f} / Rs. {s['avg_loss']:,.2f} (R:R = {s['rr']:.2f})")
    print(f"Max drawdown        : Rs. {s['max_dd']:,.2f}")
    print("=" * 70)
    print("\nExit reasons:")
    print(trades_df["exit_reason"].value_counts().to_string())
    print("\nPer-direction trades:")
    print(trades_df["macro_type"].value_counts().to_string())


def main() -> None:
    print("Loading NIFTY 1m spot data ...")
    df_1m = load_1m_spot(START, END)
    if df_1m.empty:
        print("No NIFTY 1m spot data found in the requested range.")
        return

    print(
        f"Loaded {len(df_1m):,} 1m bars from "
        f"{df_1m['datetime'].dt.date.min()} to {df_1m['datetime'].dt.date.max()}"
    )
    print(
        f"\nRunning macro-to-micro engine | ADX<{MAX_ADX} | "
        f"RSI long>{RSI_LONG_MIN} / short<{RSI_SHORT_MAX} | VWAP={USE_VWAP}"
    )

    macro_df, trades_df = v4.backtest_macro_to_micro(
        df_1m,
        multipliers=MULTIPLIERS,
        lookback=3,
        max_adx=MAX_ADX,
        rsi_long_min=RSI_LONG_MIN,
        rsi_short_max=RSI_SHORT_MAX,
        use_vwap=USE_VWAP,
        use_adx=USE_ADX,
        use_rsi=USE_RSI,
    )

    print_macro_table(macro_df)
    print_trade_summary(trades_df)

    out_macro = os.path.join(OUTPUT_DIR, f"nifty_macro_traps_{START}_{END}.csv")
    out_trades = os.path.join(OUTPUT_DIR, f"nifty_macro_to_micro_trades_{START}_{END}.csv")
    macro_df.to_csv(out_macro, index=False)
    trades_df.to_csv(out_trades, index=False)
    print(f"\nSaved macro table to {out_macro}")
    print(f"Saved trade log to {out_trades}")


if __name__ == "__main__":
    main()
